version: '3'

services:
  db:
    container_name: database
    image: postgres
    environment:
      PGDATA: /tmp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "pw12345"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
